name: flutter_email_js
description: A new Flutter Package to integrated Email Js service easily into your flutter project.
version: 1.0.3
homepage: "https://github.com/javedmughal-058/flutter_email_js"

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  http: ^1.1.0
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

